apiVersion: v1
kind: Service
metadata:
  name: sandstore-headless
  labels:
    app: sandstore
    app.kubernetes.io/name: sandstore
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: sandstore
  ports:
    - name: raft
      port: 8080
      targetPort: 8080
      protocol: TCP
