apiVersion: v1
kind: Service
metadata:
  name: sandstore-nodeport
  labels:
    app: sandstore
    app.kubernetes.io/name: sandstore
spec:
  type: NodePort
  selector:
    app: sandstore
  ports:
    - name: client
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
