apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sandstore-local-ssd
provisioner: docker.io/hostpath
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
